# Generated by Django 5.2.13 on 2026-04-19 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professionals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professional',
            name='company_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='professional',
            name='job_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
